name: Hello

on: 
 push:
  branches:
    - main

jobs:

  greet:
   runs-on: ubuntu-latest
   steps:
     - name: say hello to users
       run: echo "Hello Bhavik"

     - name: say hello to username
       run: echo "Hello $USER"
  details:
   runs-on: ubuntu-latest
   steps:
     - name: show what version of python and node and Docker
       run: node -v && python --version && docker --version
